version: "3.9"

services:
  postgres-db:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: currency_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    ports:
      - "5433:5432"