spring:
 application:
   name: currency-exchanger
 datasource:
   url: jdbc:postgresql://localhost:5433/currency_project
   username: postgres
   password: changeme
   driver-class-name: org.postgresql.Driver
 liquibase:
   change-log: classpath:db/changelog/v1_init_db.sql
 jpa:
   show-sql: true
   properties:
     hibernate:
       format_sql: true
server:
  port: 8080

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

openex:
  api:
    key: "036ba538768d4da584d94cb80e00f338"
